### PR TITLE
Update handler.js

### PR DESCRIPTION
**Pull request by bertho-zero**
Fix this error:
```
        socket._feathers.body = {};
                              ^

TypeError: Cannot set property 'body' of undefined
```

### CODE REVIEW

**Comment by daffl** [comment]
When is that error happening?

**Comment by bertho-zero** [comment]
- I initialize socket.io with autoConnect option set to false
- I open socket
- I run app.anthenticate() with expired token

**Comment by bertho-zero** [comment]
Without this pull request I need to add the following code for my app to work:

```js
app.io.on('connection', socket => {
  if (!socket._feathers) {
    socket._feathers = {};
  }
}
```

**Comment by daffl** [comment]
Ok, I'll try to reproduce and create a test case for it. I don't believe I ran into this so it's probably the `autoConnect` setting.

**Pull request closed without merging**
